#pragma once

#define CAN_PACKET_ID__E_STOP                0x00
#define CAN_PACKET_ID__HEARTBEAT             0x01
#define CAN_PACKET_ID__VERSION               0x02
#define CAN_PACKET_ID__LIMIT_SWITCH_ALERT    0x03 
#define CAN_PACKET_ID__STEPPER_DRIVE_RAD     0x04
#define CAN_PACKET_ID__BLDC_INPUT_MODE       0x05
#define CAN_PACKET_ID__BLDC_INPUT_POSITION   0x06
#define CAN_PACKET_ID__BLDC_INPUT_VELOCITY   0x07
#define CAN_PACKET_ID__BLDC_DIRECT_WRITE     0x08
#define CAN_PACKET_ID__BLDC_DIRECT_READ      0x09
#define CAN_PACKET_ID__BLDC_ENCODER_ESTIMATE 0x0a
